//
//  Workspace.swift
//  Config
//
//  Created by YunhakLee on 10/1/25.
//

import Foundation
import ProjectDescription

let workspace = Workspace(
    name: "WSS-iOS-V2",
    projects: [
        "Projects/**"
    ],
    schemes: [
        .scheme(
            name: "WSS-DEBUG",
            shared: true,
            buildAction: .buildAction(targets: [
                .project(path: "Projects/App", target: "WSS-DEBUG")
            ]),
            runAction: .runAction(configuration: .debug)
        ),
        .scheme(
            name: "WSS-RELEASE",
            shared: true,
            buildAction: .buildAction(
                targets: [
                    .project(path: "Projects/App", target: "WSS-RELEASE")
                ],
            ),
            runAction: .runAction(configuration: .release)
        )
    ],
    generationOptions: .options(autogeneratedWorkspaceSchemes: .disabled)
)
